### ISSUE TITLE
Ctrl-click Is reinitialising the window a bit too harshly

### ISSUE THREAD

**Issue by DaluS** [ToFuProject/datastock#2]
If ctrl-click 
![image](https://user-images.githubusercontent.com/11523050/155557684-0bc69aef-a00e-4fad-b757-35ea78a5bfbf.png)

Resizing the window is cleaning this issue

**Comment by Didou09** [comment]
OK, thanks,

That's due to the interactivity which forces to blit the axes (i.e. redraw parts of them at each event) and means resizing / zooming / moving has to be managed by the library.
Will try to fix in next version :-)
